export const VIETNAMESE_BANKS = [
  { id: "vcb", name: "Vietcombank", fullName: "Ngân hàng TMCP Ngoại thương Việt Nam" },
  { id: "tcb", name: "Techcombank", fullName: "Ngân hàng TMCP Kỹ thương Việt Nam" },
  { id: "bidv", name: "BIDV", fullName: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam" },
  { id: "ctg", name: "VietinBank", fullName: "Ngân hàng TMCP Công Thương Việt Nam" },
  { id: "mbb", name: "MB Bank", fullName: "Ngân hàng TMCP Quân đội" },
  { id: "vpb", name: "VPBank", fullName: "Ngân hàng TMCP Việt Nam Thịnh Vượng" },
  { id: "tpb", name: "TPBank", fullName: "Ngân hàng TMCP Tiên Phong" },
  { id: "acb", name: "ACB", fullName: "Ngân hàng TMCP Á Châu" },
  { id: "stb", name: "Sacombank", fullName: "Ngân hàng TMCP Sài Gòn Thương Tín" },
  { id: "vib", name: "VIB", fullName: "Ngân hàng TMCP Quốc tế Việt Nam" },
  { id: "hdb", name: "HDBank", fullName: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh" },
  { id: "shb", name: "SHB", fullName: "Ngân hàng TMCP Sài Gòn - Hà Nội" },
  { id: "msb", name: "MSB", fullName: "Ngân hàng TMCP Hàng Hải Việt Nam" },
  { id: "ocb", name: "OCB", fullName: "Ngân hàng TMCP Phương Đông" },
  { id: "scb", name: "SCB", fullName: "Ngân hàng TMCP Sài Gòn" },
  { id: "lpbank", name: "LPBank", fullName: "Ngân hàng TMCP Lộc Phát Việt Nam" },
  { id: "seabank", name: "SeABank", fullName: "Ngân hàng TMCP Đông Nam Á" },
  { id: "abbank", name: "ABBANK", fullName: "Ngân hàng TMCP An Bình" },
  { id: "oceanbank", name: "OceanBank", fullName: "Ngân hàng Thương mại TNHH MTV Đại Dương" },
  { id: "agribank", name: "Agribank", fullName: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam" },
  { id: "pvcombank", name: "PVcomBank", fullName: "Ngân hàng TMCP Đại Chúng Việt Nam" },
  { id: "bacabank", name: "Bac A Bank", fullName: "Ngân hàng TMCP Bắc Á" },
  { id: "namabank", name: "Nam A Bank", fullName: "Ngân hàng TMCP Nam Á" },
  { id: "ncb", name: "NCB", fullName: "Ngân hàng TMCP Quốc Dân" },
  { id: "vietabank", name: "VietABank", fullName: "Ngân hàng TMCP Việt Á" },
  { id: "vietcapitalbank", name: "BVBank", fullName: "Ngân hàng TMCP Bản Việt" },
  { id: "kienlongbank", name: "Kienlongbank", fullName: "Ngân hàng TMCP Kiên Long" },
  { id: "saigonbank", name: "SaigonBank", fullName: "Ngân hàng TMCP Công Thương Sài Gòn" },
  { id: "pgbank", name: "PGBank", fullName: "Ngân hàng TMCP Thịnh vượng và Phát triển" },
  { id: "vietbank", name: "Vietbank", fullName: "Ngân hàng TMCP Việt Nam Thương Tín" },
  { id: "baovietbank", name: "BaoViet Bank", fullName: "Ngân hàng TMCP Bảo Việt" },
  { id: "gpbank", name: "GPBank", fullName: "Ngân hàng TM TNHH MTV Dầu Khí Toàn Cầu" },
  { id: "vrb", name: "VRB", fullName: "Ngân hàng Liên doanh Việt - Nga" },
  { id: "ivb", name: "IVB", fullName: "Ngân hàng TNHH Indovina" },
  { id: "publicbank", name: "Public Bank", fullName: "Ngân hàng TNHH MTV Public Việt Nam" },
  { id: "shinhambank", name: "Shinhan Bank", fullName: "Ngân hàng TNHH MTV Shinhan Việt Nam" },
  { id: "standardchartered", name: "Standard Chartered", fullName: "Ngân hàng TNHH MTV Standard Chartered Việt Nam" },
  { id: "hsbc", name: "HSBC", fullName: "Ngân hàng TNHH MTV HSBC Việt Nam" },
  { id: "uob", name: "UOB", fullName: "Ngân hàng TNHH MTV United Overseas Bank Việt Nam" },
  { id: "wooribank", name: "Woori Bank", fullName: "Ngân hàng TNHH MTV Woori Việt Nam" },
  { id: "cimb", name: "CIMB", fullName: "Ngân hàng TNHH MTV CIMB Việt Nam" },
  { id: "cake", name: "Cake by VPBank", fullName: "Ngân hàng số Cake by VPBank" },
  { id: "uubank", name: "Ubank", fullName: "Ngân hàng số Ubank by VPBank" },
  { id: "timo", name: "Timo", fullName: "Ngân hàng số Timo by Bản Việt" },
  { id: "vneipt", name: "VNPT Money", fullName: "Ví điện tử VNPT Money" },
  { id: "viettelmoney", name: "Viettel Money", fullName: "Ví điện tử Viettel Money" },
  { id: "momo", name: "MoMo", fullName: "Ví điện tử MoMo" },
  { id: "zalopay", name: "ZaloPay", fullName: "Ví điện tử ZaloPay" },
];
